apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-mbza
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-mbza@sha256:1599c056830fc549123c072691544b7fffdbe8978deebd7308a049c68ee11613
        name: my-nodejs
        resources: {}
status: {}
